onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - core-js
  - esbuild
  - protobufjs
  - sharp

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.11: '>=16.0.11'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  undici@<6.23.0: '>=6.23.0'
